### PR TITLE
Add housesof.world website

### PR DESCRIPTION
**Pull request by flayks**
I thought it could be nicely listed here ✌️
Sorry for the other PR, not sure what happened there!

### CODE REVIEW

**Comment by janosh** [comment]
No problem, I could have merged #78 even with the head repo (your fork) deleted.

But same question as in #78, is the site's source code public?

**Comment by flayks** [comment]
Sorry I forgot to reply to your question, it is not public no 😅

**Comment by janosh** [comment]
There were a few closed-source sites added when this repo initially got started. But with the number of SvelteKit sites exploding and the purpose of this collection being a learning resource where interested developers can look at implementation details of every project, all new sites should be open source. Any chance you want to change your repo to public?

**Comment by flayks** [comment]
As it is a side and passion project, I'm not really sure if we'll put it open-source to be fair. I can understand, no big deal, I was just considering it as my portfolio is also in the list.

**Comment by janosh** [comment]
> I can understand, no big deal, I was just considering it as my portfolio is also in the list.

I know and this site looks great too. It would definitely fit here. It's a great show case for animations and I can definitely see it being a source of inspiration for other devs. If it's a side project, why not make it public?

**Comment by flayks** [comment]
It's rather a product and a bigger thing than a side project for fun, bundling quite a lot of our skills and work that we would not like to reveal fully. Also as a matter of lack of experience with the open source world, code documentation and organization it wouldn't be adapted. No worries if this doesn't fit though, I will consider resubmitting a site if it's open-source ✌️

**Comment by janosh** [comment]
I see. I'll merge this for now. Would be great if you can revisit this and add a repo URL if the code ever goes public.

**Pull request merged**
