### PR TITLE
Add team-health-check-coral.vercel.app

### PR DESCRIPTION
**Pull request by codehub-kirans**
https://github.com/codehub-kirans/team-health-check

### CODE REVIEW

**Comment by janosh** [comment]
Thanks for the submission! 👍 

I think this largely overlaps with existing resources already in `awesome-sveltekit`. The entry requirements have gotten stricter over time. We're now looking for new ideas, use cases and designs not covered by existing items in this collection.

**Comment by codehub-kirans** [comment]
Thanks for the feedback. May I know what the entry requirements may be? It would be good to have them listed in the contribution guidelines. At a cursory glance, none of the projects listed on awesome-sveltekit seems to have any implementation with Pocketbase as a backend and UI with picoCSS.

**Comment by janosh** [comment]
> May I know what the entry requirements may be? It would be good to have them listed in the contribution guidelines.

Excellent suggestion. See [c653722](https://github.com/janosh/awesome-sveltekit/commit/c653722840778c54f8ed0d411ae6a639c6bc7155).

> At a cursory glance, none of the projects listed on awesome-sveltekit seems to have any implementation with Pocketbase as a backend and UI with picoCSS.

Oh, I missed Pocketbase. That's interesting. Happy to take "Team Health Check".

**Comment by codehub-kirans** [comment]
> > May I know what the entry requirements may be? It would be good to have them listed in the contribution guidelines.
> 
> Excellent suggestion. See [c653722](https://github.com/janosh/awesome-sveltekit/commit/c653722840778c54f8ed0d411ae6a639c6bc7155).

Nice!

> 
> > At a cursory glance, none of the projects listed on awesome-sveltekit seems to have any implementation with Pocketbase as a backend and UI with picoCSS.
> 
> Oh, I missed Pocketbase. That's interesting. Happy to take "Team Health Check".

That's great! Updated the PR. 👍

**Comment by janosh** [comment]
Thanks. 👍

**Pull request merged**
