### PR TITLE
Add Mission Patch website

### PR DESCRIPTION
**Pull request by floehopper**
https://mission-patch.com/

This app was built using SvelteKit for the frontend and AWS CDK for the serverless backend. I'm afraid the GitHub repo is private at the moment, so I can't add that. Apologies if this is disqualifying!

### CODE REVIEW

**Comment by janosh** [comment]
Any chance the repo is going public in the near future? With few exceptions, being open source has become a requirement for projects in this collection.

**Comment by floehopper** [comment]
Ah, OK. It might do, but I can't say for sure. If that's a hard requirement, it might be better to close this for now and we can always bring it back to life later.

**Comment by janosh** [comment]
> If that's a hard requirement, it might be better to close this for now and we can always bring it back to life later.

I agree, definitely open to that.

Since this collection is meant as a learning resource for Svelte devs, a closed-source site can at most serve as inspiration. The educational value just isn't there.

**Comment by floehopper** [comment]
> Since this collection is meant as a learning resource for Svelte devs, a closed-source site can at most serve as inspiration. The educational value just isn't there.

That's totally fair enough 👍

It would be good to make the open-source requirement a bit clearer in the "Open to Suggestions" section of the website where it says "See something that's missing from this list? PRs welcome!" I did look through the existing sites and saw that some don't have a repo listed, so I thought you might accept closed-source projects...

Closing for now.

**Comment by floehopper** [comment]
It's a great resource BTW! 😍

**Comment by janosh** [comment]
> It would be good to make the open-source requirement a bit clearer in the "Open to Suggestions" section of the website where it says "See something that's missing from this list? PRs welcome!"

That's an excellent point! 👍  I'll push a fix later.

> It's a great resource BTW! 😍

I'm glad if it's helpful. 😄

**Pull request closed without merging**
