### PR TITLE
Add barnsworthburning.net

### PR DESCRIPTION
**Pull request by Aias**
This PR proposes adding [barnsworthburning.net](https://barnsworthburning.net/) to the list of sites. It also adds two new technologies:
- [Airtable](https://www.airtable.com/) – Used as the backing database, as well as the `airtable.js` API
- [Radix](https://www.radix-ui.com/colors) – Or more specifically the Radix color palette for dynamic theming

Barnsworthburning does not meet the 50-star requirement, but I think it could be included here for its distinctive approach to networked digital gardening. The UI itself is highly crafted with great attention to detail and a number of novel interaction patterns. It's also built on Svelte 5 and Sveltekit v2, so serves as an example of the (currently) most up-to-date Svelte syntax and practices.

A great review of an older iteration of the site (not by me) can be found here: https://www.kickscondor.com/barnsworthburning/

image
image

Thank you for your consideration, and let me know if I missed anything in this PR!

### CODE REVIEW

**Comment by Aias** [comment]
Getting an error installing dependencies:

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: awesome-sveltekit@0.1.0
npm error Found: eslint@9.8.0
npm error node_modules/eslint
npm error   dev eslint@"^9.[6](https://github.com/janosh/awesome-sveltekit/actions/runs/10132014634/job/28015430411#step:4:7).0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^8.56.0" from typescript-eslint@[7](https://github.com/janosh/awesome-sveltekit/actions/runs/10132014634/job/28015430411#step:4:8).17.0
npm error node_modules/typescript-eslint
npm error   dev typescript-eslint@"^7.15.0" from the root project
```

It appears that [typescript-eslint is close to supporting eslint 9](https://github.com/typescript-eslint/typescript-eslint/issues/8211), but not quite there. The currently specified versions have a mismatch. I could downgrade the eslint version to 8 for now for compatibility?

**Comment by janosh** [comment]
thanks for this addition! having a svelte v5 and kit v2 site would be great. the [auto-generated screenshot](https://github.com/janosh/awesome-sveltekit/blob/473e9ff78ba1a24632a29487afdf970c510e64b5/site/static/screenshots/barnsworthburning.avif) only shows a cloudflare bot filter page. anything you can do about that?

**Comment by Aias** [comment]
> thanks for this addition! having a svelte v5 and kit v2 site would be great. the [auto-generated screenshot](https://github.com/janosh/awesome-sveltekit/blob/473e9ff78ba1a24632a29487afdf970c510e64b5/site/static/screenshots/barnsworthburning.avif) only shows a cloudflare bot filter page. anything you can do about that?

@janosh thanks for adding! On the screenshot, I recently started using cloudflare and not super familiar with how to allow only certain bots - I've noticed that it sometimes blocks pretty benign ones like RSS feed checkers too, etc. Do you happen to know if there's a user agent or IP address I could look for to add it to an allow list? Or if I could provide a manually-generated screenshot?

**Comment by janosh** [comment]
> Or if I could provide a manually-generated screenshot?

sure, that's probably easiest. please make sure it's in `.avif` format

**Comment by Aias** [comment]
@janosh Manually updated the screenshots for the site. I also was able to find the IP of the screenshot generator and added it to my cloudflare allow list, so it might work now anyway.

**Pull request merged**
