### PR TITLE
Add Duplicate Word Finder

### PR DESCRIPTION
**Pull request by finnhvman**

### CODE REVIEW

**Comment by janosh** [comment]
Looks great! Could you add a repo URL?

**Comment by finnhvman** [comment]
> Looks great! Could you add a repo URL?

Sorry, it's a private repo

**Comment by janosh** [comment]
Would you consider making it public? [That's a requirement](https://github.com/janosh/awesome-sveltekit#-open-to-suggestions) for all additions to this collection.

**Comment by finnhvman** [comment]
Sorry, I don't want to. I built the original version (vanilla js) on CodePen 4 years ago, and I found like 20 sites that simply copied my code.

**Comment by janosh** [comment]
> Sorry, I don't want to.

No worries, up to you.

> I built the original version (vanilla js) on CodePen 4 years ago, and I found like 20 sites that simply copied my code.

Yeah, happens all the time. But unless you were planning to monetize the tool, does it matter? And if you are planning to monetize it wouldn't be a good fit for this collection.

**Comment by finnhvman** [comment]
Let's say I don't want to give up on the idea of monetization yet. Thanks for considering though!

**Pull request closed without merging**
