### PR TITLE
Kitcommerce repo added

### PR DESCRIPTION
**Pull request by itswadesh**

### CODE REVIEW

**Comment by janosh** [comment]
Thanks, good work!

You may want to remove Sapper from your GH keywords:

Screen Shot 2022-08-23 at 08 39 52

**Comment by itswadesh** [comment]
Thanks for the info. Updated GH keywords.

**Comment by janosh** [comment]
Off topic but curious since I see [you're using `svelte-select`](https://github.com/itswadesh/svelte-commerce/blob/df5eb41c9685ea162ddc690f17aab4d259a9d204/src/routes/checkout/add-address/%2Bpage.svelte#L200-L206). I wrote [`svelte-multiselect`](https://github.com/janosh/svelte-multiselect) and was wondering if you've tried that? If so, I'd be interested in how they compare and if you have suggestions for improvement.

**Comment by itswadesh** [comment]
Thanks Janosh, I will give it a try. Have been struggling with svelte-select for some reason.

**Pull request merged**
